spring:
  redis:
        #数据库索引
        database: 0
        host: 47.103.13.140
        port: 6379
        password: root123
        jedis:
          pool:
            #最大连接数
            max-active: 8
            #最大阻塞等待时间(负数表示没限制)
            max-wait: -1ms
            #最大空闲
            max-idle: 8
            #最小空闲
            min-idle: 0
        #连接超时时间
        timeout: 10000ms
  cache:
    redis:
        use-key-prefix: true
        key-prefix: dev
        cache-null-values: false
        time-to-live: 20s